#ABNF 1.0 UTF-8;
language zh-CN; 
mode voice;

root $main;
$main =[我] [$want]  [$ask]  [酒店] [$Irrelevent1] [酒店] [$go] ( $movement | $opera | $location | $content) [$Irrelevent2] ;
$want = 想 | 需要 | 可以;
$ask = 知道 | 请问 | 问 | 了解;
$Irrelevent1 = 怎么 | 在哪里 |  有哪些 | 几点 |  哪里有 | 什么时候 | 如何 ;
$go = 去 | 要 | 到 | 向 | 走;
$movement = 前进 |后退 |原地左转| 原地右转 | 前进左转 | 前进右转 ;
$opera = 点餐服务 | 洗衣服务  | 点餐 | 洗衣 | 用餐 | 退房 | 入住;
$content = 入住时间 | 退房时间 | 押金 | 房型 | 入住 | 退房 | 用餐时间  | 洗衣时间 | 点餐时间 | 寄存行李;
$location = 电梯 |楼梯 | 餐厅 | 中餐厅 | 西餐厅 |  健身房 |  会议室 | 失物招领处 | 行李寄存处 | 附近银行 | 附近商场 | 附近机场 | 娱乐中心 | 咖啡馆 | 附近地铁;
$Irrelevent2 = 怎么走 | 在哪里 | 那里 | 有哪些 |是几点 | 是多少 | 多少钱 | 如何走;


